version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python:
      - "3.12"
      - "3.11"
      - "3.10"
      - "3.9"      

env:
  GEMINI_API_KEY: ${GEMINI_API_KEY}
  
python:
  install:
    - .

# sphinx:
#   configuration: docs/conf.py
