version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
    python: "3.11"
    python: "3.10"
    python: "3.9"

env:
  GEMINI_API_KEY: ${GEMINI_API_KEY}
  
python:
  install:
    - path: .

# sphinx:
#   configuration: docs/conf.py
